import type {Metadata} from 'next';
import { Inter } from 'next/font/google'; // Using Inter from Google Fonts
import './globals.css';
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({
  variable: '--font-inter', // Using a consistent variable name
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'MarkMaster',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}> {/* Use the new font variable */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
